services:
  stremio-ai-search:
    image: ghcr.io/cedya77/stremio-ai-search:latest
    build: 
      context: https://github.com/itcon-pty-au/stremio-ai-search.git
      dockerfile: Dockerfile
    container_name: stremio-ai-search
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 7000 # needed when using community image
    expose:
      - 7000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremio-ai-search.rule=Host(`${STREMIO_AI_SEARCH_HOSTNAME}`)"
      - "traefik.http.routers.stremio-ai-search.entrypoints=websecure"
      - "traefik.http.routers.stremio-ai-search.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stremio-ai-search.middlewares=authelia@docker"
      - "traefik.http.services.stremio-ai-search.loadbalancer.server.port=7000"
    profiles:
      - stremio-ai-search
      - all
